version: '3'
services:
  web:
    image: node:14 
    container_name: express-api 
    working_dir: /app
    command: npm start
    volumes:
      - ./app:/app
    ports:
      - "3000:3000" 
    environment:
      - MONGO_URL=mongodb://mongo:27017/express-api
    depends_on:
      - mongo
    networks:
      - api-network

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - api-network

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"  # Port sur lequel Swagger UI sera accessible
    environment:
      - SWAGGER_JSON=/app/swagger.json  # Le chemin vers votre fichier swagger.json
    volumes:
      - ./swagger.json:/app/swagger.json  # Montez votre fichier swagger.json

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'

networks:
  api-network:
    driver: bridge
